Repository availproject/docs, pull requests merged in 2023-11, with the labels that each got.

#145 chore: test links and more for CoN release
  docs/about/identity.md
Labels: type/footprint, type:chore

#139 Initial light client draft for new testnet
  docs/operate/node/0010-light-client.md
Labels: topic/node/lc, type/enhancement

#147 Add contract details for goldberg network.
  docs/api/validiums.md
Labels: type/enhancement, topic/build/validiums

#148 feat: rollup-centric and general avail content
  docs/about/introduction.md
  docs/about/introduction/appid.md
  docs/about/introduction/light-clients.md
  docs/about/introduction/validiums.md
  docs/build/app-chain.md
  docs/build/op-rollup.md
  docs/build/overview.md
  docs/build/validium.md
  docs/build/volition.md
  docs/build/zk-rollup.md
  docs/exploration.md
  sidebars.js
  src/components/Home.js
Labels: topic/use/general, type/refactor, type/enhancement, topic/general

#149 update: CoN challenges page
  docs/clash-of-nodes/challenges.md
  docs/networks.md
Labels: type/enhancement

#155 Added steps to rotate session keys using docker
  docs/operate/validator/0030-staking.md
Labels: type/enhancement, topic/node/general

#156 feat: zkevm-based validium
  docs/build/op-stack/op-stack.md
  docs/build/op-stack/overview.md
  docs/build/zkevm/overview.md
  docs/build/zkevm/zkevm.md
  sidebars.js
Labels: type/new-page, type/enhancement, topic/build/validiums

#162 Correction of internal links by Cumulo
  docs/operate/node/0010-light-client.md
Labels: type/footprint

#173 Updated Node from v1.8.0.2 to v1.8.0.3
  docs/build/quickstart.md
  docs/networks.md
  docs/operate/node/0030-full-node-docker.md
  docs/operate/requirements.md
  docs/operate/validator/0020-validator-node-docker.md
  docs/operate/validator/0030-staking.md
Labels: type/enhancement, topic/node/general
