Repository availproject/docs, pull requests merged in 2023-10, with the labels that each got.

#116 update: node v1.7.1 & lc v1.7.0
  docs/build/quickstart.md
  docs/operate/requirements.md
  docs/operate/validator/0030-staking.md
  src/data/content-data.js
Labels: type:chore

#118 update: node hosting info for node types
  docs/operate/node-types.md
Labels: type/enhancement, topic/node/general

#124 chore: fix typos
  docs/about/introduction/validiums.md
  docs/api/light-client/light-client-embedding.md
  docs/api/light-client/using-light-client.md
  docs/operate/requirements.md
  docs/operate/validator/0070-chilling.md
Labels: type/footprint

#125 update: LC to v.1.7.2 & Node to v1.7.1
  docs/operate/requirements.md
  src/data/content-data.js
Labels: type/footprint

#126 updates to exploration page change request
  docs/exploration.md
  sidebars.js
Labels: type/enhancement

#127 feat: initial ci
  .github/workflows/build.yml
Labels: type:chore

#128 feat: init lint checks
  .github/workflows/build.yml
  .husky/pre-commit
  .prettierrc
  README.md
  docs/about/accounts.md
  docs/about/explorer.md
  docs/about/faucet.md
  docs/about/introduction.md
  docs/about/introduction/appid.md
  docs/about/introduction/light-clients.md
  docs/about/introduction/validiums.md
  docs/api/light-client/light-client-embedding.md
  docs/api/light-client/using-light-client.md
  docs/api/validiums.md
  docs/build/app-chain.md
  docs/build/op-rollup.md
  docs/build/quickstart.md
  docs/build/validium.md
  docs/build/volition.md
  docs/build/zk-rollup.md
  docs/index.mdx
  docs/operate/node-types.md
  docs/operate/node/0010-light-client.md
  docs/operate/node/0020-full-node-binaries.md
  docs/operate/node/0030-full-node-docker.md
  docs/operate/node/0040-rpc-node.md
  docs/operate/node/0050-bootstrap-node.md
  docs/operate/node/0060-relay-node.md
  docs/operate/requirements.md
  docs/operate/validator/0000-already-running-full-node.md
  docs/operate/validator/0010-validator-node-binaries.md
  docs/operate/validator/0020-validator-node-docker.md
  docs/operate/validator/0030-staking.md
  docs/operate/validator/0040-backup-node.md
  docs/operate/validator/0050-validator-monitoring.md
  docs/operate/validator/0060-validator-upgrade.md
  docs/operate/validator/0070-chilling.md
  docusaurus.config.js
  package.json
  sidebars.js
  src/components/ButtonLink.js
  src/components/EcosystemSection.js
  src/components/FAQAccordion.js
  src/components/FAQSection.js
  src/components/HeadSection.js
  src/components/Home.js
  src/components/TutorialsCard.js
  src/css/bootstrap-only-grid.min.css
  src/css/custom.css
  src/css/footer.scss
  src/data/content-data.js
  src/theme/Footer/index.js
  src/theme/Toggle/index.js
  src/theme/Toggle/styles.module.css
  static/form.html
  static/grafana/Avail-Node-Metrics.json
  static/kate/chainspec.raw.json
  yarn.lock
Labels: type:chore

#130 feat: spell check
  .github/workflows/build.yml
  cspell.json
  docs/operate/validator/0050-validator-monitoring.md
Labels: type:chore

#131 update: homepage styling updates
  docs/faqs.md
  sidebars.js
  src/components/EcosystemSection.js
  src/components/Home.js
  src/css/custom.css
  src/data/content-data.js
Labels: type/enhancement

#132 LC 1.7.2 config.yaml
  static/kate/avail-light-1.7.2/config.yaml
Labels: topic/node/lc, type/new-page

#133 update: lc & full node to v1.7.2
  CNAME
  docs/build/quickstart.md
  docs/operate/node/0030-full-node-docker.md
  docs/operate/requirements.md
  docs/operate/validator/0020-validator-node-docker.md
  src/data/content-data.js
  static/kate/avail-light-1.4.3/config.yaml
Labels: type/enhancement, topic/node/general

#134 update: codeblock styling
  src/css/custom.css
Labels: type/enhancement

#135 update: further homepage styling improvements
  docs/networks.md
  docs/operate/node/0010-light-client.md
  docs/operate/requirements.md
  docusaurus.config.js
  src/components/Home.js
  src/components/TutorialsCard.js
  src/data/content-data.js
Labels: type/enhancement, type:chore

#136 update: sidebar styling
  docs/networks.md
  docusaurus.config.js
  sidebars.js
  src/css/custom.css
Labels: type/enhancement

#137 update: common and additional styling improvements
  docusaurus.config.js
  sidebars.js
  src/components/Home.js
  src/css/custom.css
  src/data/content-data.js
Labels: type/enhancement

#138 update: node & lc content enh
  docs/build/quickstart.md
  docs/networks.md
  docs/operate/node/0010-light-client.md
  docs/operate/requirements.md
  docusaurus.config.js
Labels: topic/node/lc, type/enhancement, topic/node/general

#140 feat: announcement bar
  docusaurus.config.js
  src/css/custom.css
Labels: type/enhancement

#141 Fix some typos
  cspell.json
  docs/operate/validator/0010-validator-node-binaries.md
  docs/operate/validator/0070-chilling.md
Labels: type/footprint

#119 add: exploration team page
  docs/exploration.md
  sidebars.js
Labels: type/new-page

#103 Glossary for the docs
  docs/faqs.md
  docs/glossary.md
  sidebars.js
  yarn.lock
Labels: type/new-page, need/change

#142 update: enhance lc homepage card
  docs/networks.md
  src/data/content-data.js
Labels: type/enhancement
